services:
  - type: worker
    name: telegram-bot-kate
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python render_start.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: ANONYMOUS_QUESTION_LINK
        sync: false 